services:
    Redgem\ServicesIOBundle\Lib\View\Service:
        public: true
        arguments:
            $container: '@service_container'

    Redgem\ServicesIOBundle\Lib\Model\Service:
        public: true
        arguments:
            $container: '@service_container'

    Redgem\ServicesIOBundle\Lib\Model\Listener:
        public: true
        arguments:
            $model: '@Redgem\ServicesIOBundle\Lib\Model\Service'
            $router: "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    Redgem\ServicesIOBundle\Lib\Http\Service:
        public: true
        arguments:
            $monolog: "@logger"
            $config: "%servicesio_http%"
            $httpLogger: '@Redgem\ServicesIOBundle\Lib\Http\Profiler\Logger'

    Redgem\ServicesIOBundle\Lib\Http\Profiler\Logger:
        public: true